project:
  type: website

website:
  title: "From The Desk of Rylyn"
  site-url: https://rylynwill.github.io/DeskOfRylyn/
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format: 
  html:
    theme: sketchy
    css: styles.css

editor: visual
output:
  quarto::quarto_docx:
    base_format: quarto::quarto

