project:
  type: website

website:
  title: "Clairvoyant Data Scientis"
  site-url: https://rylynwill.github.io/ReadTheRoom/
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format: 
  html:
    theme: sketchy
    css: styles.css

editor: visual

